version: '3.3'

services:

    mariadb:
        image: mariadb
        environment:
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin123
            - MYSQL_DATABASE=matchdata
            - MYSQL_ROOT_PASSWORD=admin123
            - MYSQL_ROOT_HOST=%
        volumes:
            - ./mariadb:/var/lib/mysql 
        ports:
            - "3308:3306"
        networks:
            django_net:
                ipv4_address: 172.19.0.2

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            django_net:
                ipv4_address: 172.19.0.4

    django:
        image: django
        build: ./django
        depends_on:
            - mariadb
        ports:
            - "8000:8000"
            - "8082:80"
        volumes:
            - /opt/data
        environment:
            ALLOWED_HOSTS: "*"

        networks:
            django_net:
                ipv4_address: 172.19.0.3

        command: ["bash", "/root/scripts/entrypoint.sh"]

networks:
    django_net:
        ipam:
            driver: default
            config:
               - subnet: 172.19.0.0/16

